language: node_js
sudo: false

node_js:
  - '6'
  - '8'
  - '10'

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  - yarn test
